# Generated by Django 5.1.5 on 2025-01-28 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(help_text='Enter your name', max_length=50)),
                ('customer_Email', models.EmailField(max_length=254, unique=True)),
                ('customer_details', models.CharField(help_text='Enter your details', max_length=100)),
                ('customer_Number', models.IntegerField(help_text='Enter your Number')),
                ('customer_DOB', models.DateField(help_text='Enter your DOB')),
                ('customer_Volume', models.IntegerField()),
                ('customer_Education', models.CharField(choices=[('B.Tech', 'B.Tech'), ('M.Tech', 'M.Tech'), ('P.Hd', 'P.Hd')], max_length=50)),
                ('customer_Gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=50)),
                ('customer_Image', models.ImageField(upload_to='')),
                ('customer_Resume', models.FileField(upload_to='')),
                ('password', models.CharField(max_length=50)),
                ('cpassword', models.CharField(max_length=50)),
            ],
        ),
    ]
