# Generated by Django 5.1.5 on 2025-01-29 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='customer_Image',
            field=models.ImageField(upload_to='image/'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='customer_Resume',
            field=models.FileField(upload_to='file/'),
        ),
    ]
