# Generated by Django 5.1.5 on 2025-01-29 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_registration_customer_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='customer_Email',
            field=models.EmailField(max_length=254),
        ),
    ]
