# Generated by Django 5.1.5 on 2025-01-31 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_registration_customer_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='customer_Education',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='registration',
            name='customer_Gender',
            field=models.CharField(max_length=50),
        ),
    ]
